// <auto-generated />
namespace TrainingCentersCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddImageInTeacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImageInTeacher));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281123338_AddImageInTeacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
