// <auto-generated />
namespace TrainingCentersCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_not_bind_in_tc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_not_bind_in_tc));
        
        string IMigrationMetadata.Id
        {
            get { return "201503261200049_add_not_bind_in_tc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
