
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    public AspNetUser()
    {

        this.AspNetUserClaims = new HashSet<AspNetUserClaims>();

        this.AspNetUserLogins = new HashSet<AspNetUserLogins>();

        this.AspNetRoles = new HashSet<AspNetRoles>();

    }


    public string Id { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string Discriminator { get; set; }

    public string Email { get; set; }



    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }

}

}
