<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class Certification
    {
        public Certification()
        {
<<<<<<< HEAD
            this.QualificationCertifications = new HashSet<QualificationCertification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProvider { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual CertificationProvider CertificationProvider { get; set; }
        public virtual ICollection<QualificationCertification> QualificationCertifications { get; set; }
    }
}
=======
            QualificationCertifications = new HashSet<QualificationCertification>();
        }

        public int Id { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Провайдер")]
        public int? IdProvider { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Название")]
        public string Title { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        public virtual CertificationProvider CertificationProvider { get; set; }

        public virtual ICollection<QualificationCertification> QualificationCertifications { get; set; }
    }
}
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
