
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CertificationTaking
{

    public int Id { get; set; }

    public Nullable<int> IdStudent { get; set; }

    public Nullable<int> IdCertification { get; set; }

    public Nullable<int> Date { get; set; }

    public string Result { get; set; }

}

}
