
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Certification
{

    public Certification()
    {

        this.QualificationCertifications = new HashSet<QualificationCertification>();

    }


    public int Id { get; set; }

    public Nullable<int> IdProvider { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }



    public virtual CertificationProvider CertificationProvider { get; set; }

    public virtual ICollection<QualificationCertification> QualificationCertifications { get; set; }

}

}
