<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class CertificationProvider
    {
        public CertificationProvider()
        {
<<<<<<< HEAD
            this.Certifications = new HashSet<Certification>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Certification> Certifications { get; set; }
    }
=======
            Certifications = new HashSet<Certification>();
        }

        public int Id { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Название")]
        public string Title { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Адрес")]
        public string Addres { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Телефон")]
        public string Phone { get; set; }

        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Некорректный адрес")]
        [Display(Name = "e-mail")]
        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        public string Email { get; set; }

        public virtual ICollection<Certification> Certifications { get; set; }
}

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
