//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTaking
    {
        public CourseTaking()
        {
            this.Listeners = new HashSet<Listener>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdTrainingCourse { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public string Description { get; set; }
        public string IdObecjt { get; set; }
    
        public virtual ICollection<Listener> Listeners { get; set; }
    }
}
