<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listener
    {
        public int Id { get; set; }
        public Nullable<int> IdTrainingGroup { get; set; }
        public Nullable<int> IdCourseTakings { get; set; }
    
        public virtual CourseTaking CourseTaking { get; set; }
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Listener
    {
        public int Id { get; set; }

        public int? IdTrainingGroup { get; set; }

        public int? IdCourseTakings { get; set; }

        public virtual CourseTaking CourseTaking { get; set; }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
        public virtual TrainingGroup TrainingGroup { get; set; }
    }
}
