
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Menu
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Link { get; set; }

    public string IdTrainingCenter { get; set; }

    public int Parent_Id { get; set; }

    public int Ord_Id { get; set; }

}

}
