<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class Qualification
    {
        public Qualification()
        {
<<<<<<< HEAD
            this.QualificationCertifications = new HashSet<QualificationCertification>();
            this.QualificationTrainingCours = new HashSet<QualificationTrainingCour>();
            this.QualificationVacancies = new HashSet<QualificationVacancy>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public int ParentId { get; set; }
    
        public virtual ICollection<QualificationCertification> QualificationCertifications { get; set; }
        public virtual ICollection<QualificationTrainingCour> QualificationTrainingCours { get; set; }
        public virtual ICollection<QualificationVacancy> QualificationVacancies { get; set; }
    }
=======
            QualificationCertifications = new HashSet<QualificationCertification>();
            QualificationTrainingCours = new HashSet<QualificationTrainingCour>();
        }

        public int Id { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Название")]
        public string Title { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Тип")]
        public Nullable<int> Type { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "HeadHunter Id")]
        public string HeadHunterId { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Квалификация на HeadHunter'e")]
        public string HeadHunterName { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Ключевые слова")]
        public string HeadHunterKeys { get; set; }

        [Display(Name="Статья, связанная с квалификацией")]
        public int? ArticleId { get; set; }

        [Display(Name = "Статья, связанная с квалификацией")]
        public Article ArticleQualification { get; set; }

        public Nullable<int> ParentId { get; set; }
        public virtual ICollection<QualificationCertification> QualificationCertifications { get; set; }

        public virtual ICollection<QualificationTrainingCour> QualificationTrainingCours { get; set; }

        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
