
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class QualificationVacancy
{

    public int Id { get; set; }

    public Nullable<int> IdQualification { get; set; }

    public Nullable<int> IdVacancy { get; set; }



    public virtual Qualification Qualification { get; set; }

    public virtual Vacancy Vacancy { get; set; }

}

}
