<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationCertification
    {
        public int Id { get; set; }
        public Nullable<int> IdQualification { get; set; }
        public Nullable<int> IdCertification { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual Qualification Qualification { get; set; }
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("QualificationCertification")]
    public partial class QualificationCertification
    {
        public int Id { get; set; }

        public int? IdQualification { get; set; }

        public int? IdCertification { get; set; }

        public virtual Certification Certification { get; set; }

        public virtual Qualification Qualification { get; set; }
        public virtual Qualification Qualifications { get; set; }
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    }
}
