<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class TrainingGroup
    {
        public TrainingGroup()
        {
<<<<<<< HEAD
            this.HoldCourses = new HashSet<HoldCours>();
            this.Listeners = new HashSet<Listener>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTrainingCourse { get; set; }
        public string EstimateOfExpenditures { get; set; }
        public Nullable<int> IdObject { get; set; }
    
        public virtual ICollection<HoldCours> HoldCourses { get; set; }
        public virtual ICollection<Listener> Listeners { get; set; }
    }
=======
            HoldCourses = new HashSet<HoldCours>();
            Listeners = new HashSet<Listener>();
        }

        public int Id { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Учебный курс")]
        public Nullable<int> IdTrainingCourse { get; set; }

        [StringLength(255, ErrorMessage = "Смета затрат")]
        [Display(Name = "Название")]
        public string EstimateOfExpenditures { get; set; }

        public int? IdObject { get; set; }

        public virtual ICollection<HoldCours> HoldCourses { get; set; }

        public virtual ICollection<Listener> Listeners { get; set; }

    }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
