<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCourseTeacher
    {
        public int Id { get; set; }
        public Nullable<int> IdTrainingCourse { get; set; }
        public Nullable<int> IdTeacher { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual TrainingCours TrainingCours { get; set; }
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class TrainingCourseTeacher
    {
        public int Id { get; set; }

        public int? IdTrainingCourse { get; set; }

        public int? IdTeacher { get; set; }

        public virtual Teacher Teacher { get; set; }

        public virtual TrainingCenterCours TrainingCours { get; set; }
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    }
}
