
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingCours
{

    public TrainingCours()
    {

        this.CourseModules = new HashSet<CourseModule>();

        this.HoldCourses = new HashSet<HoldCours>();

        this.QualificationTrainingCours = new HashSet<QualificationTrainingCour>();

        this.RelatedCourses = new HashSet<RelatedCours>();

        this.RelatedCourses1 = new HashSet<RelatedCours>();

        this.TrainingCenterCourses = new HashSet<TrainingCenterCours>();

        this.TrainingCourseTeachers = new HashSet<TrainingCourseTeacher>();

        this.ScheduleTtrainingCourses = new HashSet<ScheduleTtrainingCours>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string ShortDescription { get; set; }

    public Nullable<int> Hourse { get; set; }

    public Nullable<decimal> PriceForOrganizations { get; set; }

    public Nullable<decimal> PriceForIndividuals { get; set; }

    public Nullable<decimal> CostOfOneHourForOrganizations { get; set; }

    public Nullable<decimal> CostOfOneHourForIndividuals { get; set; }

    public Nullable<int> LevelOfDifficulty { get; set; }

    public string RequiredPreliminaryPreparation { get; set; }

    public string MandatoryPreliminaryPreparation { get; set; }

    public Nullable<int> IdTraningCenter { get; set; }

    public Nullable<int> IdObject { get; set; }



    public virtual ICollection<CourseModule> CourseModules { get; set; }

    public virtual ICollection<HoldCours> HoldCourses { get; set; }

    public virtual ICollection<QualificationTrainingCour> QualificationTrainingCours { get; set; }

    public virtual ICollection<RelatedCours> RelatedCourses { get; set; }

    public virtual ICollection<RelatedCours> RelatedCourses1 { get; set; }

    public virtual ICollection<TrainingCenterCours> TrainingCenterCourses { get; set; }

    public virtual ICollection<TrainingCourseTeacher> TrainingCourseTeachers { get; set; }

    public virtual ICollection<ScheduleTtrainingCours> ScheduleTtrainingCourses { get; set; }

}

}
