<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class TrainingCenter
    {
        public TrainingCenter()
        {
<<<<<<< HEAD
            this.TrainingCenterCourses = new HashSet<TrainingCenterCours>();
            this.TrainingCenterTeachers = new HashSet<TrainingCenterTeacher>();
        }
    
        public int Id { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Description { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<TrainingCenterCours> TrainingCenterCourses { get; set; }
        public virtual ICollection<TrainingCenterTeacher> TrainingCenterTeachers { get; set; }
    }
=======
            ScheduleTtrainingCourses = new HashSet<ScheduleTtrainingCours>();
            TrainingCenterCourses = new HashSet<TrainingCenterCours>();
            TrainingCenterTeachers = new HashSet<TrainingCenterTeacher>();
        }

        public int Id { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Адрес")]
        public string Addres { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Телефон")]
        public string Phone { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "E-mail")]
        public string Email { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Город")]
        public string Organization { get; set; }

        [Display(Name = "Общее описание центра")]
        public string Description { get; set; }

        [Display(Name = "Логотип")]
        [Column(TypeName = "image")]
        public byte[] Logo { get; set; }

        public string LogoContentType { get; set; }

        [Display(Name="Id HH")]
        public string HHCityId { get; set; }

        [Required]
        [StringLength(255)]
        public string Url { get; set; }

        public virtual ICollection<ScheduleTtrainingCours> ScheduleTtrainingCourses { get; set; }

        public virtual ICollection<TrainingCenterCours> TrainingCenterCourses { get; set; }

        public virtual ICollection<TrainingCenterTeacher> TrainingCenterTeachers { get; set; }

        public virtual ICollection<Feedback> Feedback { get; set; }

        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
