<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class TrainingModule
    {
        public TrainingModule()
        {
<<<<<<< HEAD
            this.CourseModules = new HashSet<CourseModule>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Numbers { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Topics { get; set; }
        public Nullable<int> IdTrainingCenter { get; set; }
    
        public virtual ICollection<CourseModule> CourseModules { get; set; }
    }
=======
            CourseModules = new HashSet<CourseModule>();
        }

        public int Id { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Название")]
        public string Title { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Краткое описание")]
        public string ShortDescription { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Порядковый номер в учебном курсе")]
        public int? Numbers { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Количество академических часов")]
        public int? Hours { get; set; }

        [Display(Name = "Список тем")]
        public int? Topics { get; set; }

        [Display(Name = "Учебный центр")]
        public int? IdTrainingCenter { get; set; }

        public virtual ICollection<CourseModule> CourseModules { get; set; }

    }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
