//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCenter
    {
        public TrainingCenter()
        {
            this.TrainingCenterCourses = new HashSet<TrainingCenterCours>();
            this.TrainingCenterTeachers = new HashSet<TrainingCenterTeacher>();
        }
    
        public int Id { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Description { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<TrainingCenterCours> TrainingCenterCourses { get; set; }
        public virtual ICollection<TrainingCenterTeacher> TrainingCenterTeachers { get; set; }
    }
}
