
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingGroup
{

    public TrainingGroup()
    {

        this.HoldCourses = new HashSet<HoldCours>();

        this.Listeners = new HashSet<Listener>();

    }


    public int Id { get; set; }

    public Nullable<int> IdTrainingCourse { get; set; }

    public string EstimateOfExpenditures { get; set; }

    public Nullable<int> IdObject { get; set; }



    public virtual ICollection<HoldCours> HoldCourses { get; set; }

    public virtual ICollection<Listener> Listeners { get; set; }

}

}
