
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vacancy
{

    public Vacancy()
    {

        this.QualificationVacancies = new HashSet<QualificationVacancy>();

    }


    public int Id { get; set; }

    public string Description { get; set; }

    public string Organization { get; set; }

    public Nullable<decimal> Wages { get; set; }

    public string Additionally { get; set; }

    public string Link { get; set; }



    public virtual ICollection<QualificationVacancy> QualificationVacancies { get; set; }

}

}
