<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCentersCRM.Models
{
    using System;
    using System.Collections.Generic;
    
=======
namespace TrainingCentersCRM.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    public partial class Vacancy
    {
        public Vacancy()
        {
<<<<<<< HEAD
            this.QualificationVacancies = new HashSet<QualificationVacancy>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Organization { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public string Additionally { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<QualificationVacancy> QualificationVacancies { get; set; }
    }
=======
        }

        public int Id { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Организация")]
        public string Organization { get; set; }

        [RegularExpression("[0-9]+", ErrorMessage = "Недопустимое значение")]
        [Display(Name = "Заработная плата")]
        [Column(TypeName = "money")]
        public Nullable<decimal> Wages { get; set; }

        [StringLength(1023, ErrorMessage = "Длина строки должна быть менее 1024 символов")]
        [Display(Name = "Дополнительная информация")]
        public string Additionally { get; set; }

        [StringLength(255, ErrorMessage = "Длина строки должна быть менее 256 символов")]
        [Display(Name = "Ссылка на сайт с резмещеной вакансией")]
        public string Link { get; set; }

        public int? IdTrainingCenter { get; set; }

        [Display(Name = "Учебный центр")]
        public TrainingCenter TrainingCenter { get; set; }

        public virtual ICollection<Qualification> Qualifications { get; set; }
    }

>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
}
